### ISSUE TITLE
Touch up README

### ISSUE THREAD

**Issue by em0ney** [GorillaStack/retro-tag#1]
Hi Ray,

It would be great to touch up the README with:

1. abstract - what is this all about, what do you get by using it
2. setup - more of a step-by-step guide to how one should get started

Also, it would be great if you could pick a licence (up to you, MIT, GPL and MPL are all good).

Cheers,
Elliott

**Comment by rayj-pgi** [comment]
I think we're all set here. I'm glad to have things up and running now. Thanks for the help @em0ney!
