### ISSUE TITLE
Access denied error when running the CloudFormation template which calls autotag-0.5.1.zip

### ISSUE THREAD

**Issue by gmcconne** [GorillaStack/retro-tag#15]
When you run the CloudFormation template the stack fails because you get access denied when calling GetObject to the object autotag-0.5.1.zip in a bucket I assume owned by Gorillastack named "gorillastack-autotag-releases-us-west-2".
Error message: Your access has been denied by S3, please make sure your request credentials have permission to GetObject for gorillastack-autotag-releases-us-west-2/autotag-0.5.1.zip.

**Comment by rayjanoka** [comment]
we aren't updating those s3 buckets afaik. you'll need to build the zip manually.
