### ISSUE TITLE
Question: where is the autotag_log.js file?

### ISSUE THREAD

**Issue by cherylf** [GorillaStack/retro-tag#3]
Hi, 

The Lambda function created from the autotag_retro_main-template.json template threw an error saying that it cannot find the autotag_log.js file. I zipped the whole retro-tag repo and used it as the code for the Lambda function. Is it the right thing to do or am I missing something?

**Comment by rayj-pgi** [comment]
Hi, actually we use the auto-tag project to perform the tagging. Grab the autotag-0.5.3.zip here https://github.com/GorillaStack/auto-tag/releases/tag/0.5.3 for the Lambda function.
