### ISSUE TITLE
credentials_set?': undefined method `access_key_id' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by bibek-rauniyar** [GorillaStack/retro-tag#6]
Hi 
After following the whole README .md. I am getting the below error .Can you please let me know the workaround for this.

The AwsResource::VpnGateway.get_resources cache file is too old, scanning aws...
#<Thread:0x00007f80be1374a0@./retro_tag.rb:162 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	26: from ./retro_tag.rb:168:in `block (2 levels) in <main>'
	25: from /Users/bibekroniyar/Desktop/retro-tag/auto_tag/aws_mixin.rb:19:in `write_cache_file'
	24: from /Users/bibekroniyar/Desktop/retro-tag/aws_resource/default.rb:55:in `get_resources'
	23: from /Users/bibekroniyar/Desktop/retro-tag/aws_resource/default.rb:55:in `each'
	22: from /Users/bibekroniyar/Desktop/retro-tag/aws_resource/default.rb:61:in `block in get_resources'
	21: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-ec2-1.165.0/lib/aws-sdk-ec2/client.rb:25186:in `describe_vpn_gateways'
	20: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/seahorse/client/request.rb:70:in `send_request'
	19: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
	18: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
	17: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
	16: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
	15: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	14: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
	13: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/param_validator.rb:24:in `call'
	12: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/seahorse/client/plugins/endpoint.rb:45:in `call'
	11: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/endpoint_discovery.rb:78:in `call'
	10: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/endpoint_pattern.rb:28:in `call'
	 9: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/user_agent.rb:11:in `call'
	 8: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/query/handler.rb:28:in `call'
	 7: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/retry_errors.rb:346:in `call'
	 6: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
	 5: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/transfer_encoding.rb:24:in `call'
	 4: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/signature_v4.rb:65:in `call'
	 3: from /Library/Ruby/Gems/2.6.0/gems/aws-sdk-core-3.98.0/lib/aws-sdk-core/plugins/signature_v4.rb:123:in `apply_signature'
	 2: from /Library/Ruby/Gems/2.6.0/gems/aws-sigv4-1.1.4/lib/aws-sigv4/signer.rb:206:in `sign_request'
	 1: from /Library/Ruby/Gems/2.6.0/gems/aws-sigv4-1.1.4/lib/aws-sigv4/signer.rb:661:in `fetch_credentials'
/Library/Ruby/Gems/2.6.0/gems/aws-sigv4-1.1.4/lib/aws-sigv4/signer.rb:674:in `credentials_set?': undefined method `access_key_id' for nil:NilClass (NoMethodError)
The AwsResource::VpcNetworkAcl.get_resources cache file is too old, scanning aws...
Traceback (most recent call last):

**Comment by rayjanoka** [comment]
Hi @Bibek-DevOps, how are you executing the script as in which arguments are you sending?
