### ISSUE TITLE
Unable to GetObject to gorillastack-autotag-releases-us-west-2 S3 Bucket during CloudFormation Stack creation

### ISSUE THREAD

**Issue by GeorgeDavis-TM** [GorillaStack/retro-tag#8]
I am trying to run the AutoTagRetro CloudFormation template but it keeps failing when it tries to GetObject to the us-west-2 S3 bucket.

**Error Message -**

`Your access has been denied by S3, please make sure your request credentials have permission to GetObject for gorillastack-autotag-releases-us-west-2/autotag-0.5.1.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: 114772cd-66f0-4432-951e-60fa02852d4a; Proxy: null)`

<img width="1279" alt="Screen Shot 2021-01-28 at 11 45 35 AM" src="https://user-images.githubusercontent.com/64860010/106170738-c2536f00-615e-11eb-9c8a-69dd8f6e9d6a.png">

Please advise about S3 bucket access.

Thank you.

**Comment by GeorgeDavis-TM** [comment]
Update: I was able to workaround the issue for now by downloading the latest autotag package (autotag-0.5.3.zip) from GitHub releases and hosting it in an S3 Bucket within my AWS Account to proceed with the CloudFormation template.

**Comment by ecout** [comment]
This is out of scope of the code because is a permissions issue, please close.
